version: "2"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=calculadora
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  suma:
    build: ./suma
    dockerfile: Docker_suma
    ports:
    - "5001:5001"
    depends_on:
    - flask

  resta:
    build: ./resta
    dockerfile: Docker_resta
    ports:
    - "5002:5002"
    depends_on:
    - flask

  multi:
    build: ./multi
    dockerfile: Docker_multi
    ports:
    - "5003:5003"
    depends_on:
    - flask

  div:
    build: ./div
    dockerfile: Docker_div
    ports:
    - "5004:5004"
    depends_on:
    - flask